version: '3.8'

services:
  web:
    image: weather-api
    container_name: weather-api
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - '-c'
      - 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001'
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:14.2
    container_name: weather-api-db
    environment:
      - DATABASE_URL=postgres://postgres:213697@localhost:5432/weather"
    volumes:
      - weather-api-db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  weather-api-db-data: