# Generated by Django 5.0.1 on 2024-01-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('pressure', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wind_speed', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
